-- Databricks notebook source
-- MAGIC %python
-- MAGIC # dbutils.widgets.text("outSchema", "mat_analysis")

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS $outSchema.msds_v2_snomedcodes
(
        V2_Table           STRING,
        V2_DataItemName    STRING,
        V2_Schema          STRING,
        V2_Table2          STRING,
        SNOMED_Schema      STRING,
        SNOMED_Code        STRING, 
        V2_CategoryNumber  STRING,
        SNOMED_Description STRING
        
)
USING DELTA
PARTITIONED BY (SNOMED_Schema, V2_Schema)
;

-- COMMAND ----------

TRUNCATE TABLE $outSchema.msds_v2_snomedcodes

-- COMMAND ----------

-- DBTITLE 1,Master SNOMED codes required 
INSERT INTO $outSchema.msds_v2_snomedcodes

VALUES
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 84457005','1','Spontaneous onset of labor (finding) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 408818004','3','  Induction of labor by artificial rupture of membranes (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 408817009','3','Amniotomy at delivery (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177129005','3','Surgical induction of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 288141009','4','  Fetal head - manual flexion (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 288191008','4','  Induction of labor by injection into upper limb (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 288039005','4','  Internal cephalic version and extraction (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237001001','4','Augmentation of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 288190009','4','Induction of labor by intravenous drip (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 288189000','4','Induction of labor by intravenous injection (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237006006','4','Internal conversion of face to vertex (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237005005','4','Manual procedure for malpresentation or position (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 112927003','4','Manual rotation of fetal head (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 31208007','4','Medical induction of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237000000','4','Modification of uterine activity (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode','177135005','4','Oxytocin induction of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177136006','4','Prostaglandin induction of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237007002','4','Reposition of a prolapsed arm (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 225245001','4','Rubbing up a contraction (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 236971007','4','Stabilizing induction (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237002008','4','Stimulation of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 308037008','4','Syntocinon induction of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 240281005','5','Air embolization of fetus (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 240282003','5','Cardiac puncture and fetal exsanguination (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 72059007','5','Destructive procedure on fetus to facilitate delivery (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177095006','5','Early selective feticide (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237013006','5','Embryotomy (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 62726004','5','Fetal clavicotomy (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 386562007','5','Fetal cranioclasis (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 386561000','5','Fetal craniotomy (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 304968002','5','Fetal Danforth operation (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 20891002','5','Fetal decapitation (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 240283008','5','Fetal intracardiac injection of potassium chloride (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237012001','5','Freeing the posterior arm (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177096007','5','Late selective feticide (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237008007','5','Maneuvers for delivery in shoulder dystocia (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237009004','5','McRoberts maneuver (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 240284002','5','Multifetal pregnancy reduction (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 265633004','5','Selective destruction of fetus (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 707849001','5','Selective destruction of fetus using ultrasonographic guidance (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237010009','5','Suprapubic pressure on fetal shoulder (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 237011008','5','Woods screw maneuver (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 408816000','5','Artificial rupture of membranes (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177130000','5','Forewater rupture of amniotic membrane (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177131001','5','Hindwater rupture of amniotic membrane (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 236958009','5','Induction of labor (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177141003','2','Elective cesarean section (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 177143000','2','Elective lower segment cesarean section (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 736026009','2','Elective lower segment cesarean section with bilateral tubal ligation (procedure) '),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode',' 11466000','2','Cesarean section (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','248870002','01','Vagina finding (finding) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','249221003','02','Labial tear (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','46311005','02','Perineal laceration involving fourchette (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','76658000','02','Perineal laceration involving labia (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','301858009','02','Repair of labial tear (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199979008','03','Obstetric high vaginal laceration - delivered (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199977005','03','Obstetric high vaginal laceration (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199980006','03','Obstetric high vaginal laceration with postnatal problem (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','248882006','03','Scarring of vaginal wall (finding) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','262935001','03','Tear of vaginal wall (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','397786004','03','Vaginal hernia (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','289517005','03','Vaginal lesion (finding) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','275430007','03','Vaginal muscle tear (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','249220002','03','Vaginal tear resulting from childbirth (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','262936000','03','Vaginal vault tear (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','248878009','03','Vaginal wall finding (finding) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','57759005','04','First degree perineal laceration (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199916005','04','First degree perineal tear during delivery - delivered (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199917001','04','First degree perineal tear during delivery with postnatal problem (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','85542007','04','Perineal laceration involving skin (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','79839005','04','Perineal laceration involving vulva (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','11942004','05','Perineal laceration involving pelvic floor (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','9107002','05','Perineal laceration involving perineal muscles (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','6234006','05','Second degree perineal laceration (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199925004','05','Second degree perineal tear during delivery - delivered (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199926003','05','Second degree perineal tear during delivery with postnatal problem (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','10217006','06','Third degree perineal laceration (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199930000','06','Third degree perineal tear during delivery - delivered (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199931001','06','Third degree perineal tear during delivery with postnatal problem (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','449807005','06','Type 3a third degree laceration of perineum (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','449808000','06','Type 3b third degree laceration of perineum (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','449809008','06','Type 3c third degree laceration of perineum (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','399031001','07','Fourth degree perineal laceration (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','16950007','07','Fourth degree perineal laceration involving anal mucosa (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','34262005','07','Fourth degree perineal laceration involving rectal mucosa (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199934009','07','Fourth degree perineal tear during delivery - delivered (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199935005','07','Fourth degree perineal tear during delivery with postnatal problem (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','40219000','08','Delivery by Malstroms extraction with episiotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','26313002','08','Delivery by vacuum extraction with episiotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','63407004','08','Episioproctotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','85548006','08','Episiotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','15413009','08','High forceps delivery with episiotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','17860005','08','Low forceps delivery with episiotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','25828002','08','Mid forceps delivery with episiotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','236992007','08','Right mediolateral episiotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','288194000','08','Routine episiotomy and repair (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','36497006','08','Traumatic extension of episiotomy (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','246422006','08','Type of episiotomy (attribute) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','202745004','09','Annular tear of cervical disc (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','237090005','09','Cervical laceration (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','25032009','09','Failed attempted abortion with laceration of cervix (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','18872002','09','Illegal abortion with laceration of cervix (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','609469009','09','Induced termination of pregnancy complicated by laceration of cervix (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199972004','09','Laceration of cervix - obstetric (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','7166002','09','Legal abortion with laceration of cervix (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199974003','09','Obstetric laceration of cervix - delivered (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','199975002','09','Obstetric laceration of cervix with postnatal problem (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','281911004','09','Teardrop fracture of cervical vertebra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','210213008','10','Closed injury of urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','283918002','10','Contusion of urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','448768004','10','Injury of bladder and urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','262916001','10','Injury of female urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','22724000','10','Injury of urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','283922007','10','Laceration of urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','288208001','10','Obstetric bladder/urethra damage (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','210217009','10','Open injury of urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','53212003','10','Postobstetric urethral stricture (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','283920004','10','Transection of urethra (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','86347007','10','Traumatic urethral stricture (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','237329006','10','Urethra injury - obstetric (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','74944002','10','Urethral false passage (disorder) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','79824009','11','Suture of clitoris (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','68011001','11','Clitoridotomy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','118860007','11','Procedure on clitoris (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','39845007','12','Anterior colporrhaphy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','359924008','12','Anterior colporrhaphy for repair of cystocele without repair of urethrocele (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','314487008','12','Anterior mesh vaginal repair (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','236857000','12','Colpoperineorrhaphy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','13910004','12','Combined anteroposterior colporrhaphy (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','359927001','12','Repair of cystocele (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','238034001','12','Repair of vaginal wall prolapse (procedure) '),
('MSD302','GENITAL TRACT TRAUMATIC LESION','GenitalTractTraumaticLesion','MSD302','MasterSnomedCTProcedureCode','289906003','01','Female genital tract problem (finding)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','236974004','01','Instrumental birth'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','236974004','02','Suspected fetal compromise without instruments'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','11037005','03','Prevention of uncontrolled/serious tearing'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','893721000000103','04','Female genital mutilation not resolved during the Antenatal period'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','287976008','01',' Breech/instrumental delivery operations (procedure)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','15413009','01','High forceps delivery with episiotomy (procedure)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','40219000','01','Delivery by Malstroms extraction with episiotomy (procedure)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','26313002','01','Delivery by vacuum extraction with episiotomy (procedure)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','63407004','01','Episioproctotomy (procedure)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','17860005','01','Low forceps delivery with episiotomy (procedure)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','236992007','01','Right mediolateral episiotomy (procedure)'),
('MSD302','EPISIOTOMY REASON','EpisiotomyReason','MSD302','MasterSnomedCTProcedureCode','288194000','01','Routine episiotomy and repair (procedure)'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','50697003','01','General anaesthetic'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','67716003','02','Epidural or caudal anaesthetic'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','231249005','03','Spinal anaesthetic'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','68248001','09','Pudendal block anaesthetic'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','171789006','02','Therapeutic sacral epidural injection (procedure)'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','67716003','02','Epidural injection of anesthetic substance, therapeutic, caudal, continuous (procedure)'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','16388003','03','Injection of spinal anesthetic agent for analgesia (procedure)'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','231208005','09','Pudendal nerve block - transvaginal (procedure)'),
('MSD302','ANAESTHESIA TYPE IN LABOUR AND DELIVERY','LabourAnaesthesiaType','MSD302','MasterSnomedCTProcedureCode','231209002','09','Pudendal nerve block: transperineal (procedure)'),
('MSD302','ARTIFICIAL RUPTURE OF MEMBRANES REASON','AROM','MSD302','MasterSnomedCTProcedureCode','408818004','01','Induction of labor by artificial rupture of membranes (procedure)'),
('MSD302','ARTIFICIAL RUPTURE OF MEMBRANES REASON','AROM','MSD302','MasterSnomedCTProcedureCode','237001001','02','Augmentation of labor (procedure)'),
('MSD302','ARTIFICIAL RUPTURE OF MEMBRANES REASON','AROM','MSD302','MasterSnomedCTProcedureCode','','03','Improve fetal assessment'),
('MSD302','OXYTOCIN ADMINISTERED INDICATOR','OxytocinAdministeredInd','MSD302','MasterSnomedCTProcedureCode','177135005','04','Oxytocin induction of labor (procedure)'),
('MSD302','OXYTOCIN ADMINISTERED INDICATOR','OxytocinAdministeredInd','MSD302','MasterSnomedCTProcedureCode','308037008','04','Syntocinon induction of labor (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','237235009','01','Undiagnosed breech (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','719051004','02','Quantity of postpartum maternal blood loss (observable entity)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','719051004','03','Quantity of postpartum maternal blood loss (observable entity)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','719051004','04','Quantity of postpartum maternal blood loss (observable entity)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','','05','Return to theatre'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','236886002','06','Hysterectomy (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','33211000','07','Complication of anesthesia (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','305351004','08','Admission to intensive care unit (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','429098002','09','Thromboembolism of vein (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','59282003','10','Pulmonary embolism (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','274126009','11','Failed forceps/ventouse (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','17263003','12','Amniotic fluid embolism (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','116141005','06','Abdominal hysterectomy (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','288043009','06','Hysterectomy in pregnancy (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','236887006','06','Laparoscopic hysterectomy (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','116140006','06','Total hysterectomy (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','398042001','07','Accidental dural puncture (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','405361005','07','Excessive spread of local anesthetic (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','397785000','07','Neuromuscular block problem (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','65409004','07','Obstetrical complication of anesthesia (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','405368004','07','Regional blockade - excessive cephalad spread of local anesthesia (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','305352006','08','Admission to adult intensive care unit (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','183446009','08','Admission to cardiac intensive care unit (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','183449002','08','Admission to metabolic intensive care unit (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','183448005','08','Admission to neurological intensive care unit (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','183447000','08','Admission to respiratory intensive care unit (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','397945004','08','Unexpected admission to intensive care unit (procedure)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','213309003','09','Thromboembolism after infusion (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','706870000','10','Acute pulmonary embolism (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','200284000','10','Obstetric pulmonary embolism (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','5010004','12','Amniotic fluid embolism following molar AND/OR ectopic pregnancy (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','10835781000119105','12','Amniotic fluid embolism in childbirth (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','200294005','12','Amniotic fluid pulmonary embolism - delivered (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','200295006','12','Amniotic fluid pulmonary embolism - delivered with postnatal complication (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','200296007','12','Amniotic fluid pulmonary embolism with antenatal complication (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','200297003','12','Amniotic fluid pulmonary embolism with postnatal complication (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','11454006','12','Failed attempted abortion with amniotic fluid embolism (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','609458006','12','Induced termination of pregnancy complicated by amniotic fluid embolism (disorder)'),
('MSD302','MATERNAL CRITICAL INCIDENT TYPE','MCIType','MSD302','MasterSnomedCTProcedureCode','10058006','12','Miscarriage with amniotic fluid embolism (disorder)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','230065006','1','Chain smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','230057008','1','Cigar consumption'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','59978006','1','Cigar smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','65568007','1','Cigarette smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','230063004','1','Heavy cigarette smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','160605003','1','Heavy cigarette smoker (20-39 cigs/day)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','56771006','1','Heavy smoker (over 20 per day)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','230060001','1','Light cigarette smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','160603005','1','Light cigarette smoker (1-9 cigs/day)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','169940006','1','Maternal tobacco abuse'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','427189007','1','Maternal tobacco use'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','230062009','1','Moderate cigarette smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','160604004','1','Moderate cigarette smoker (10-19 cigs/day)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','56578002','1','Moderate smoker (20 or less per day)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','230059006','1','Occasional cigarette smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','82302008','1','Pipe smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','160619003','1','Rolls own cigarettes'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','449345000','2','Smoked before confirmation of pregnancy'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','77176002','1','Current smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','365981007','1','Smoking'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','266918002','1','Tobacco smoking consumption'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','110483000','1','Tobacco user'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','266920004','1','Trivial cigarette smoker (less than one cigarette/day)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','230064005','1','Very heavy cigarette smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','160606002','1','Very heavy cigarette smoker (40+ cigs/day)'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','735128000','2','Ex-smoker for less than 1 year'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','160617001','5','Stopped smoking'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','449369001','3','Stopped smoking before pregnancy'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','449368009','2','Stopped smoking during pregnancy'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','160618006','5','Current non-smoker'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','266919005','6','Never smoked tobacco'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','702979003','6','Never used tobacco'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','711563001','6','No known exposure to tobacco smoke'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','8392000','5','Non-smoker (finding) '),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','105541001','6','Non-smoker for medical reasons'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','105539002','6','Non-smoker for personal reasons'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','105540000','6','Non-smoker for religious reasons'),
('MSD101','SMOKING STATUS AT BOOKING','SmokingStatusBooking','MSD202','MasterSnomedCTFindingCode','405746006','9','Current non smoker but past smoking history unknown'),
('MSD405','APGAR SCORE','ApgarScore','MSD405','MasterSnomedCTObsCode','249228009','0-10','Total apgar score (observable entity)'),
('MSD405','APGAR SCORE','ApgarScore','MSD405','MasterSnomedCTObsCode','169895004','0-10','Apgar score at 1 minute (observable entity)'),
('MSD405','APGAR SCORE','ApgarScore','MSD405','MasterSnomedCTObsCode','169909004','0-10','Apgar score at 5 minutes (observable entity)'),
('MSD405','APGAR SCORE','ApgarScore','MSD405','MasterSnomedCTObsCode','169922007','0-10','Apgar score at 10 minutes (observable entity)'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','237235009','01','Undiagnosed breech (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','236886002','06','Hysterectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','288043009','06','Hysterectomy in pregnancy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','236887006','06','Laparoscopic hysterectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','236890000','06','Laparoscopic procedure (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','450559006','06','Laparoscopic excision of leiomyoma of uterus (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','822191000000101','06','Laparoscopic laser myomectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','431316002','06','Laparoscopic subtotal hysterectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','236889009','06','Laparoscopic supracervical hysterectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','767751001','06','Laparoscopic adenomyomectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','713157005','06','Laparoscopic resection of uterine cornua (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','236888001','06','Laparoscopic total hysterectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','236891001','06','Laparoscopic radical hysterectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','708878003','06','Laparoscopic radical hysterectomy using robotic assistance (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','414575003','06','Laparoscopic total abdominal hysterectomy and bilateral salpingo-oophorectomy (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','446679008','06','Total laparoscopic excision of uterus by abdominal approach (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','305351004','08','Admission to intensive care unit (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','305352006','08','Admission to adult intensive care unit (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','397945004','08','Unexpected admission to intensive care unit (procedure) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','59282003','10','Pulmonary embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','706870000','10','Acute pulmonary embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','58123006','10','Failed attempted abortion with pulmonary embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','82153002','10','Miscarriage with pulmonary embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','198663000','10','Complete miscarriage with embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','198650006','10','Incomplete miscarriage with embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','200284000','12','Obstetric pulmonary embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','17263003','12','Amniotic fluid embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','5010004','12','Amniotic fluid embolism following molar AND/OR ectopic pregnancy (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','200294005','12','Amniotic fluid pulmonary embolism - delivered (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','200295006','12','Amniotic fluid pulmonary embolism - delivered with postnatal complication (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','200296007','12','Amniotic fluid pulmonary embolism with antenatal complication (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','200297003','12','Amniotic fluid pulmonary embolism with postnatal complication (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','11454006','12','Failed attempted abortion with amniotic fluid embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','609458006','12','Induced termination of pregnancy complicated by amniotic fluid embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','38905006','12','Illegal abortion with amniotic fluid embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','27015006','12','Legal abortion with amniotic fluid embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','10058006','12','Miscarriage with amniotic fluid embolism (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','2475076011','12','Amniotomy to induce labour'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','2475288019','12','Amniotomy to induce labor'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','744441019','12','Amniotic fluid embolism (disorder)'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','29186013','12','Amniotic fluid embolism'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','478094014','12','Amniotic fluid pulmonary embolism'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','47821001','02,03,04','is postpartum'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','27214003','02,03,04','Atonic postpartum hemorrhage (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','1033591000000101','02,03,04','Major postpartum haemorrhage (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','1033571000000100','02,03,04','Minor postpartum haemorrhage (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','23171006','02,03,04','Delayed AND/OR secondary postpartum hemorrhage (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','200025008','02,03,04','Secondary postpartum hemorrhage - delivered with postnatal problem (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','111452009','02,03,04','Postpartum afibrinogenemia with hemorrhage (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','49177006','02,03,04','Postpartum coagulation defect with hemorrhage (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','724496000','02,03,04','Postpartum hemorrhage co-occurrent and due to uterine rupture following obstructed labor (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','119891000119105','02,03,04','Postpartum hemorrhage due to total placenta previa (disorder) '),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','785322012','02,03,04','Postpartum hemorrhage (disorder)'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','1216656013','02,03,04','PPH - Postpartum haemorrhage'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','1218146019','02,03,04','PPH - Postpartum hemorrhage'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','79691012','02,03,04','Postpartum hemorrhage'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','494929013','02,03,04','Postpartum haemorrhage'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','1230526013','02,03,04','Bleeding postpartum'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','719051004','02,03,04','Quantity of postpartum maternal blood loss (observable entity)'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','3314819019','02,03,04','Quantity of postpartum maternal blood loss (observable entity)'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','3314820013','02,03,04','Quantity of postpartum maternal blood loss'),
('MSD302','MASTER SNOMED CT OBSERVATION CODE','MasterSnomedCTObsCode','MSD302','MasterSnomedCTObsCode','494930015','02,03,04','Haemorrhage after delivery of fetus'),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode','1105781000000106','2','Misoprostol induction of labour (procedure)'),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode','1105791000000108','1','Mifepristone induction of labour (procedure)'),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode','65497008','8','Incision of perineum (procedure)'),
('MSD302','MEDICAL INDUCTION OF LABOUR METHOD','LabourInductionMethod','MSD302','MasterSnomedCTProcedureCode','61586001','1','Delivery by vacuum extraction (procedure)')

-- COMMAND ----------

-- SELECT count(*)

-- from MAT_ANALYSIS.msds_v2_snomedcodes

-- COMMAND ----------

-- ALTER TABLE mat_analysis.msds_v2_snomedcodes OWNER TO `data-managers`